### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by dyipon** [caponetto/teachable-machine-playground#1]
Hi,

I just found your article about nail-biting thanks for sharing!
Is there any chance if you can help me to debug?

I followed your article:
- trained on Teachable Machine , and it was working at the end, its clearly detected my face
- cloned the repo, overwrote your json and .bin files
- started the webserver

But it does not recognize if i biting my nail (or just put my hands before my face).
If I put the `notify(MESSAGE_STOP);` before detecting, I get the nofication, so I don't think if its the browser's issue.
Is there any way to debug the detecting?

thanks

**Comment by dyipon** [comment]
aah, I forgot to set normal/nail-biting class names :/
its working now, thanks!

**Comment by caponetto** [comment]
I'm glad it is working @dyipon!

**Comment by dyipon** [comment]
@caponetto may I ask are you using/used it for hours? It's killing my i7/16GB laptop, chrome constantly using 50% CPU, temperature is around 70C :) (im using ubuntu)

**Comment by caponetto** [comment]
I haven't used it for hours but I can imagine such a scenario.
Maybe you can try increasing the `updateInterval` [here](https://github.com/caponetto/teachable-machine-playground/blob/main/src/pages/NailBitingDetectorPage.tsx#L38).
